import 'package:get/get.dart';

class Messages extends Translations {
	@override
	Map<String, Map<String, String>> get keys => {
		'en_US': {
			'community': 'Community',
			'darkmode':"Dark mode",
			'language':"Language",
			'typeTime':"Time style",
			'time':"Time",
			'settings':"Settings",
			'setting':"Setting",
			'custommerSp':"Custommer support",
			'payOfService':"Pay for services",
			'userInfor':"User information",
			"signout":"Sign out",
			"signin":"Sign in",
			"Logintoyouraccounttojoinustohelpyou":"Log in to your account to join us to help you:",
			"Storeandsynchronizeeventsanddataontheapponalldevices":" 👉 Store and synchronize events and data on the app on all devices",
			"WhenyouusethePerpetualCalendar,youagreetoourpoliciesandterms":"When you use the Lich Van Nien, you agree to our policies and terms",
			"SigninwithGoogle":"Sign in with Google",
			"SigninwithFacebook":"Sign in with Facebook",
			"Loginerror":"Login error",
			"Pleasetryagain":"Please try again",
			"Yourevent!":"Your event!",
			"T2":"Mon",
			"T3":"Tue",
			"T4":"Wed",
			"T5":"Thu",
			"T6":"Fri",
			"T7":"Sat",
			"CN":"Sun",
			"year":"Year",
			"month":"Month",
			"day":"Day",
			"noworktoday":"No work today",
			"Createevent":"Create event",
			"lan":"en",
			"startadiscussion":"Start a discussion",
			"detailpost":"Detail post",
			"reply":"Reply",
			"like":"Like",
			"Nointernetconnection":"No internet connection",
			"Pleaseconnecttotheinternetandtryagain":"Please connect to the internet and try again",
			"Perpetualcalendar":"Perpetual calendar",
			"Today":"Today",
		},
		'vi_VN': {
			'community': 'Cộng đồng',
			'darkmode':"Chế độ dark mode",
			'language':"Ngôn ngữ",
			'typeTime':"Kiểu đồng hồ",
			'time':"Thời gian",
			'settings':"Cài đặt chung",
			'setting':"Cài đặt",
			'custommerSp':"Hỗ trợ khách hàng",
			'payOfService':"Nạp tiền cho các dịch vụ",
			'userInfor':"Thông tin cá nhân",
			"signin":"Đăng nhập",
			"signout":"Đăng xuất",
			"Logintoyouraccounttojoinustohelpyou":"Đăng nhập tài khoản để tham gia với chúng tôi giúp bạn:",
			"Storeandsynchronizeeventsanddataontheapponalldevices":" 👉 Lưu trữ, đồng bộ các sự kiện và dữ liệu trên app ở mọi thiết bị ",
			"WhenyouusethePerpetualCalendar,youagreetoourpoliciesandterms":"Khi bạn sử dụng Lịch Vạn Niên, bạn đồng ý với các chính sách và điều khoản của chúng tôi",
			"SigninwithGoogle":"Đăng nhập với Google",
			"SigninwithFacebook":"Đăng nhập với Facebook",
			"Loginerror":"Lỗi đăng nhập",
			"Pleasetryagain":"Vui lòng thử lại",
			"Yourevent!":"Sự kiện của bạn!",
			"T2":"T2",
			"T3":"T3",
			"T4":"T4",
			"T5":"T5",
			"T6":"T6",
			"T7":"T7",
			"CN":"CN",
			"year":"Năm",
			"month":"Tháng",
			"day":"Ngày",
			"noworktoday":"Hôm nay không có công việc nào",
			"Createevent":"Tạo sự kiện",
			"lan":"vi",
			"startadiscussion":"Bạn đang gặp vấn đề ??",
			"detailpost":"Chi tiết bài viết",
			"reply":"Phản hồi",
			"like":"Thích",
			"Nointernetconnection":"Không có kết nối internet",
			"Pleaseconnecttotheinternetandtryagain":"Vui lòng kết nối internet và thử lại",
			"Perpetualcalendar":"Lịch vạn niên",
			"Today":"Hôm nay"
		}
	};
}